### ISSUE TITLE
謝謝你的上課筆記&心得

### ISSUE THREAD

**Issue by azole** [yichentsaicamille/git-workshop#2]
小小修正一點：是 Linux 指令，不是 Linus 指令喔，Linus 是 Linux 的創始人，是個人名喔。

其他筆記都很棒，也謝謝你喜歡這門課，會打指令的工程師真的看起來比較厲害!!

上課如果有任何聽不懂的地方，隨時可以發問喔，一定也有其他同學跟你遇到了一樣的情況，但他們可能更害羞，或甚至是，尚未察覺到自己的問題，所以能發現自己有問題，已經是很棒的情況了，下次就把他問出來吧！

期待上課跟你的互動喔～

**Comment by yichentsaicamille** [comment]
收到! 已經改為Linux 囉，謝謝老師~~
恩恩遇到問題會趕快向老師發問，老實說這樣也能很快解惑省下很多時間^^
