### ISSUE TITLE
謝謝你的觀影心得

### ISSUE THREAD

**Issue by azole** [yichentsaicamille/git-workshop#3]
很多人都跟你一樣，覺得男生理工科比女生強，但我身邊的朋友，很多都可以證明，這可不一定呢！

不知道你有沒有看過一部電影「關鍵少數」，沒有的話，可以去 youtube 找預告來看看，這是真實故事改編的，當年很多女生在 NASA 擔任幕後英雄的角色喔。

大腦就像肌肉一樣，肌肉可以透過重訓來加以強化，那大腦當然也可以透過一些練習來讓他成長，我自己過去的教學經驗中啊，通常上課時順順的、上課練習也都沒有問題的人，學到的東西，往往會比踩到雷的人來得少一點，人都有惰性，遇到問題時，正是強迫自己學習跟多加探索思考的時候，所以，不要害怕犯錯，更重要的是，大家都差不多的，來上實體課程，最重要的就是這群一起踩雷的夥伴們，所以，請好好一起加油喔～

**Comment by yichentsaicamille** [comment]
結訓完來看老師推薦的「關鍵少數」~我也覺得現在很多不管是電影、廣告、或是連續劇，都漸漸把女生塑造很有能力的甚至比男生還厲害的形象了，所以也相信自己一定可以在程式這塊證明自己的實力！而實體課程能夠實現成就吸引力法則，和一群目標一致的好夥伴一起前進真的很棒^^
